# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Add this block to install dependencies from requirements.txt
python:
  install:
    - requirements: requirements.txt

# Build documentation using MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true  # optional: makes sure you catch broken links or other issues

# Set the Python version and install dependencies if needed
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Additional output formats
formats:
  - pdf
  - epub
