---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - build-arch:
          filters:
            branches:
              only:
                - master
      - build-ubuntu-bionic:
          filters:
            branches:
              only:
                - master

jobs:
  build-arch:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: install dependencies
          command: pacman -Sy --needed base-devel make cmake bison flex eigen boost doxygen git --noconfirm
      - checkout
      - run:
          name: build MONAA
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
  build-ubuntu-bionic:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: apt update
          command: apt-get update
      - run:
          name: install dependencies
          command: apt-get install build-essential make cmake bison flex libeigen3-dev libboost-all-dev doxygen git -y
      - checkout
      - run:
          name: build MONAA
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
