name: Boost.Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: default build
      run: |
        mkdir build
        cd build && cmake .. && make monaa unit_test tre2ta

  gcc_unit_test:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: set gcc env
      run: |
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
    - name: build and test
      run: |
        mkdir -p gcc_build
        cd gcc_build && cmake .. && make unit_test && ./unit_test

  clang_unit_test:
    runs-on: ubuntu-latest
    container: maswag/monaa-test-env
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: set clang env
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
    - name: build and test
      run: |
        mkdir -p clang_build
        cd clang_build && cmake .. && make unit_test && ./unit_test
        
  ubuntu_bionic:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: sudo apt-get install cmake bison flex libeigen3-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test    

  ubuntu_focalionic:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: sudo apt-get install cmake bison flex libeigen3-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test    
