name: CmakeLint

on:
  push:
    paths:
      - 'CMakeLists.txt'

jobs:
  cmake-lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    - name: Install cmakelint
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          cmakelint

    - name: run cmakelint
      run: |
        cmakelint ./CMakeLists.txt
