name: Integrated.Test

on:
  push:
  pull_request:

jobs:
  integrated_test:
    name: Integrated Test (${{ matrix.os_label }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_label: "Ubuntu Noble"
            runner: ubuntu-24.04
          - os_label: "Ubuntu Jammy"
            runner: ubuntu-22.04
          - os_label: "Ubuntu Noble ARM"
            runner: ubuntu-24.04-arm
          - os_label: "Ubuntu Jammy ARM"
            runner: ubuntu-22.04-arm
          - os_label: "macOS Sequoia"
            runner: macos-15
          - os_label: "macOS Sonoma"
            runner: macos-14
          - os_label: "macOS Ventura"
            runner: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake bison libbison-dev flex libfl-dev libeigen3-dev libboost-all-dev

      - name: Install required packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install eigen boost bison flex

      - name: Build and run integrated test
        run: |
          mkdir -p build
          cd build
          cmake ..
          make monaa
          ../examples/integrated_test.sh
