name: Integrated.Test

on:
  push:

jobs:
  ubuntu_noble:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install required packages
      run: sudo apt-get install cmake bison libbison-dev flex libfl-dev libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh

  ubuntu_jammy:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install required packages
      run: sudo apt-get install cmake bison libbison-dev flex libfl-dev libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh

  ubuntu_focal:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install required packages
      run: sudo apt-get install cmake bison libbison-dev flex libfl-dev libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh

  macOS_Sonoma:
    runs-on: macos-14
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install required packages
      run: brew install eigen boost bison flex
    - name: build and test
      run: |
        mkdir -p build
        export PATH="/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:$PATH"
        LDFLAGS="-L/usr/local/opt/bison/lib -L/usr/local/opt/flex/lib"
        export CPPFLAGS="-I/usr/local/opt/flex/include"
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh

  macOS_Ventura:
    runs-on: macos-13
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install required packages
      run: brew install eigen boost bison flex
    - name: build and test
      run: |
        mkdir -p build
        export PATH="/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:$PATH"
        LDFLAGS="-L/usr/local/opt/bison/lib -L/usr/local/opt/flex/lib"
        export CPPFLAGS="-I/usr/local/opt/flex/include"
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh

  macOS_Monterey:
    runs-on: macos-12
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install required packages
      run: brew install eigen boost bison flex
    - name: build and test
      run: |
        mkdir -p build
        export PATH="/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:$PATH"
        LDFLAGS="-L/usr/local/opt/bison/lib -L/usr/local/opt/flex/lib"
        export CPPFLAGS="-I/usr/local/opt/flex/include"
        cd build && cmake .. && make monaa && ../examples/integrated_test.sh        
